#!/usr/bin/env bash 

cd .. 

echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc1_cart_min2.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc1_cart_min2.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc2_cart_min2.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc2_cart_min2.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc3_cart_min2.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc3_cart_min2.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc4_cart_min2.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc4_cart_min2.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc5_cart_min2.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc5_cart_min2.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc6_cart_min2.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc6_cart_min2.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc7_cart_min2.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc7_cart_min2.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc8_cart_min2.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc8_cart_min2.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc9_cart_min2.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc9_cart_min2.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc10_cart_min2.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc10_cart_min2.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc11_cart_min2.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc11_cart_min2.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc12_cart_min2.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc12_cart_min2.R"

echo "Done!"
