#!/usr/bin/env bash 

cd .. 

echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc1_cart.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc1_cart.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc2_cart.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc2_cart.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc3_cart.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc3_cart.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc4_cart.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc4_cart.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc5_cart.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc5_cart.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc6_cart.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc6_cart.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc7_cart.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc7_cart.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc8_cart.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc8_cart.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc9_cart.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc9_cart.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc10_cart.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc10_cart.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc11_cart.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc11_cart.R"
echo "Running pgms_simrun/mcar/mdsur_obs3_smcar_sc12_cart.R" 
Rscript "pgms_simrun/mcar/mdsur_obs3_smcar_sc12_cart.R"

echo "Done!"
