#!/usr/bin/env bash 

cd .. 

echo "Running pgms_simrun/mar/mdsur_obs3_smar_sc1_cart.R" 
Rscript "pgms_simrun/mar/mdsur_obs3_smar_sc1_cart.R"
echo "Running pgms_simrun/mar/mdsur_obs3_smar_sc2_cart.R" 
Rscript "pgms_simrun/mar/mdsur_obs3_smar_sc2_cart.R"
echo "Running pgms_simrun/mar/mdsur_obs3_smar_sc3_cart.R" 
Rscript "pgms_simrun/mar/mdsur_obs3_smar_sc3_cart.R"
echo "Running pgms_simrun/mar/mdsur_obs3_smar_sc4_cart.R" 
Rscript "pgms_simrun/mar/mdsur_obs3_smar_sc4_cart.R"
echo "Running pgms_simrun/mar/mdsur_obs3_smar_sc5_cart.R" 
Rscript "pgms_simrun/mar/mdsur_obs3_smar_sc5_cart.R"
echo "Running pgms_simrun/mar/mdsur_obs3_smar_sc6_cart.R" 
Rscript "pgms_simrun/mar/mdsur_obs3_smar_sc6_cart.R"
echo "Running pgms_simrun/mar/mdsur_obs3_smar_sc7_cart.R" 
Rscript "pgms_simrun/mar/mdsur_obs3_smar_sc7_cart.R"
echo "Running pgms_simrun/mar/mdsur_obs3_smar_sc8_cart.R" 
Rscript "pgms_simrun/mar/mdsur_obs3_smar_sc8_cart.R"
echo "Running pgms_simrun/mar/mdsur_obs3_smar_sc9_cart.R" 
Rscript "pgms_simrun/mar/mdsur_obs3_smar_sc9_cart.R"
echo "Running pgms_simrun/mar/mdsur_obs3_smar_sc10_cart.R" 
Rscript "pgms_simrun/mar/mdsur_obs3_smar_sc10_cart.R"
echo "Running pgms_simrun/mar/mdsur_obs3_smar_sc11_cart.R" 
Rscript "pgms_simrun/mar/mdsur_obs3_smar_sc11_cart.R"
echo "Running pgms_simrun/mar/mdsur_obs3_smar_sc12_cart.R" 
Rscript "pgms_simrun/mar/mdsur_obs3_smar_sc12_cart.R"

echo "Done!"
