#!/usr/bin/env bash 

cd .. 

echo "Running pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc1_cart.R" 
Rscript "pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc1_cart.R"
echo "Running pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc2_cart.R" 
Rscript "pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc2_cart.R"
echo "Running pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc3_cart.R" 
Rscript "pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc3_cart.R"
echo "Running pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc4_cart.R" 
Rscript "pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc4_cart.R"
echo "Running pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc5_cart.R" 
Rscript "pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc5_cart.R"
echo "Running pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc6_cart.R" 
Rscript "pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc6_cart.R"
echo "Running pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc7_cart.R" 
Rscript "pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc7_cart.R"
echo "Running pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc8_cart.R" 
Rscript "pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc8_cart.R"
echo "Running pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc9_cart.R" 
Rscript "pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc9_cart.R"
echo "Running pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc10_cart.R" 
Rscript "pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc10_cart.R"
echo "Running pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc11_cart.R" 
Rscript "pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc11_cart.R"
echo "Running pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc12_cart.R" 
Rscript "pgms_simrun/mdsur_obs3r/mdsur_obs3r_sc12_cart.R"

echo "Done!"
